[info]

name  = "Qemu Aarch64 Virt"
model = "qemu aarch64 virt"
vendor = "qemu"

[system]

# 使用的芯片内部设备
devices = [
]

ram_regions = [
    { addr = 0x40000000, size = '2GB' }
]





